### PR TITLE
Dropbox should be called 'Dropbox'

### PR DESCRIPTION
**Pull request by mjgiarlo**
This may be somewhat pedantic, and I will grant you that, but I originally looked into this because I couldn't figure out why I was seeing "Drop Box" in the dropdown for cloud providers. Turns out it was coupled to the name of the driver, so I figured I'd just go through the codebase and refer to Dropbox consistently as "Dropbox."

### CODE REVIEW

**Comment by jcoyne** [comment]
:+1: This looks like a breaking change to me. Is that right?

**Comment by mjgiarlo** [comment]
Yes, I do believe it is because of the change to the config file, for instance.

**Comment by mbklein** [comment]
I'm fine with this change, though I'd love to see a shim that will check the config for `drop_box` and change it to `dropbox` internally at load time, with a deprecation or other appropriate warning. I'm not sure if I have time to deal with that today or not, but I can do it sometime this week. If someone else tackles it before I do, I'm happy to do a merge and release, or at least give a thumbs up for someone else to. :)

**Comment by mjgiarlo** [comment]
Please, have at it, @mbklein!

**Comment by scherztc** [comment]
I am working on the shim @mbklein mentioned.  Let me work through this for more keyboard experience.

**Comment by mjgiarlo** [comment]
@scherztc ++

**Comment by mbklein** [comment]
@scherztc ++ for doing the thing I said I could get to in a week a month later.

**Comment by scherztc** [comment]
@mbklein, @mjgiarlo  .  How is the shim?  Should I have commented it?  Put it in its own method?  Anything I could better?  Thanks.

**Comment by mjgiarlo** [comment]
Looks :ok: to me!  I defer to @mbklein.

Thanks, @scherztc

**Comment by mjgiarlo** [comment]
@scherztc If you could squash these two commits, rebase them on master, and force-push them, that'd make for an easier merge.

**Comment by scherztc** [comment]
Squashed, rebased, and pushed.

**Comment by mjgiarlo** [comment]
Thanks @scherztc!

@mbklein ?

**Pull request merged**
