### PR TITLE
Use checkbox to select all files

### PR DESCRIPTION
**Pull request by awead**
This adds support for selecting all files in a directory. Selecting a checkbox will descend into each subfolder, loading it, and selecting its files.
select-all

### CODE REVIEW

**Comment by jcoyne** [comment]
Looks good, but it would look even better with tests.

**Comment by awead** [comment]
I hear @cam156 is really good with JS tests...

**Comment by mbklein** [comment]
I tried to write a comprehensive test suite for browse-everything when we first wrote it, but I couldn't figure out how to make Jasmine work. :confused:

**Comment by awead** [comment]
I've got Jasmine working...sort of. Now I just need to figure out how to write tests...

**Comment by awead** [comment]
@jcoyne I've added Jasmine to the test suite, however as @mbklein notes, there's a lot of difficulty with getting it to work properly. In order to make the JS testable, I had to make changes to the layout of how the functions were defined. You can see that in the last commit where I have to call a function:

https://github.com/projecthydra-labs/browse-everything/commit/cee9d95f946999aa105106c273e2bf3f7b84e54c#diff-0a43a9fbdccde442ca9a8005c537e169R293

I'm not sure this is the best way to do this, and it would entail a complete rewrite of the entire JS, which is out of scope for this PR. I made these changes because we need them to fulfill at feature request on one our applications, psu-stewardship/archivesphere#27.

At this point, I'd just like to get this merged so we can cut a new release I can move on with my work. We do need to this gem's javascript into a more testable state, and I think this PR takes an initial stab at that, but it should be continued in a separate effort, and ideally by someone (other than me) who's more fluent in the language.

**Comment by jcoyne** [comment]
@awead I didn't demand a Jasmine test. How about a view test for your changes there? Have you considered a feature spec?

**Comment by awead** [comment]
@jcoyne I tried doing a feature test via poltergeist, without success.

**Comment by awead** [comment]
@jcoyne I put in a view test for the added table cell that has the checkbox.

**Comment by jcoyne** [comment]
:+1:

**Pull request merged**
